jwt:
  secret: ${JWT_SECRET}
  accessTokenExpireTime: ${JWT_ACCESS_EXPIRE_TIME}

server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
    include:
      - domain
      - common
      - batch
      - infrastructure
      - external
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.web.cors: DEBUG

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health